name = "zetazero-me"
main = "src/worker.ts"
compatibility_date = "2025-07-28"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
preview_urls = true

[cache]
enabled = true

[assets]
directory = "dist"
binding = "ASSETS"

[[routes]]
pattern = "zetazero.me"
custom_domain = true

[observability]
enabled = true

[observability.traces]
enabled = true
